version: '3.8'

services:
  backend:
    build: .
    container_name: smart_hydration_backend
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
