# Generated by Django 5.2.13 on 2026-04-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_age_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrationsession',
            name='total_water',
        ),
        migrations.AddField(
            model_name='hydrationsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
