# Generated by Django 5.2.13 on 2026-04-10 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_hydrationsession_total_water_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.hydrationsession'),
        ),
    ]
