# Generated by Django 4.2.13 on 2026-04-12 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_waterlog_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyHydrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_activity', models.CharField(max_length=20)),
                ('water_consumed_today', models.FloatField()),
                ('weather', models.CharField(max_length=20)),
                ('recommended_water_goal_ml', models.FloatField()),
                ('remaining_water_ml', models.FloatField()),
                ('predicted_hydration_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
