# Generated by Django 5.2.13 on 2026-04-12 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bodyhydrationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyhydrationrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Body Hydration Record', 'verbose_name_plural': 'Body Hydration Records'},
        ),
        migrations.AlterField(
            model_name='bodyhydrationrecord',
            name='physical_activity',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bodyhydrationrecord',
            name='predicted_hydration_level',
            field=models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bodyhydrationrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_hydration_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bodyhydrationrecord',
            name='weather',
            field=models.CharField(choices=[('Cold', 'Cold'), ('Normal', 'Normal'), ('Hot', 'Hot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hydrationsession',
            name='activity_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hydrationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
