# Generated by Django 5.2.13 on 2026-04-13 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bodyhydrationrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationsession',
            name='total_consumed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SkinHydrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_conductance', models.FloatField()),
                ('skin_temperature', models.FloatField()),
                ('ambient_temperature', models.FloatField()),
                ('predicted_hydration_level', models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_hydration_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skin Hydration Record',
                'verbose_name_plural': 'Skin Hydration Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalHydrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_status', models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], max_length=20)),
                ('advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='core.bodyhydrationrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_hydration_records', to=settings.AUTH_USER_MODEL)),
                ('skin_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='core.skinhydrationrecord')),
            ],
            options={
                'verbose_name': 'Final Hydration Record',
                'verbose_name_plural': 'Final Hydration Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
