# Generated by Django 4.2.13 on 2026-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hydrationsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyhydrationrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='finalhydrationrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skinhydrationrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='skinhydrationrecord',
            old_name='confidence_score',
            new_name='ambient_humidity',
        ),
        migrations.AddField(
            model_name='skinhydrationrecord',
            name='electrical_capacitance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skinhydrationrecord',
            name='time_of_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodyhydrationrecord',
            name='predicted_hydration_level',
            field=models.CharField(choices=[('Hydrated', 'Hydrated'), ('Warning', 'Warning'), ('Dehydrated', 'Dehydrated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='finalhydrationrecord',
            name='final_status',
            field=models.CharField(choices=[('Hydrated', 'Hydrated'), ('Warning', 'Warning'), ('Dehydrated', 'Dehydrated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skinhydrationrecord',
            name='ambient_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skinhydrationrecord',
            name='predicted_hydration_level',
            field=models.CharField(choices=[('Hydrated', 'Hydrated'), ('Dehydrated', 'Dehydrated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skinhydrationrecord',
            name='skin_conductance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skinhydrationrecord',
            name='skin_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
