# Generated by Django 5.2.13 on 2026-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bodyhydrationrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyhydrationrecord',
            name='hydration_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalhydrationrecord',
            name='final_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationsession',
            name='ambient_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationsession',
            name='ambient_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrationsession',
            name='weather',
            field=models.CharField(choices=[('Cold', 'Cold'), ('Normal', 'Normal'), ('Hot', 'Hot')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='skinhydrationrecord',
            name='hydration_percentage',
            field=models.FloatField(default=0),
        ),
    ]
